//! Currency types.

// Note that most of this file is autogenerated via the build script
// and just included here.


/// Currency item used for trading.
include!(concat!(env!("OUT_DIR"), "/", "model/currency/enum.inc.rs"));
// TODO: add some common/obvious alternative deserializations of curriencies,
// like "mirror" rather than "mir" or "eternal-orb" rather than "ete";
// this will require custom Deserialize impl (also autogenerated in build script)


// Commonly used nicknames for the currencies

pub const ALT: Currency = Currency::OrbOfAlteration;
pub const FUSE: Currency = Currency::OrbOfFusing;
pub const FUSING: Currency = Currency::OrbOfFusing;
pub const ALCH: Currency = Currency::OrbOfAlchemy;
pub const SILVER: Currency = Currency::SilverCoin;
pub const GCP: Currency = Currency::GemcuttersPrism;
pub const EXALT: Currency = Currency::ExaltedOrb;
pub const CHROME: Currency = Currency::ChromaticOrb;
pub const JEW: Currency = Currency::JewellersOrb;
pub const CHANCE: Currency = Currency::OrbOfChance;
pub const CHAOS: Currency = Currency::ChaosOrb;
pub const CHISEL: Currency = Currency::CartographersChisel;
pub const SCOUR: Currency = Currency::OrbOfScouring;
pub const BLESS: Currency = Currency::BlessedOrb;
pub const REGAL: Currency = Currency::RegalOrb;
pub const REGRET: Currency = Currency::OrbOfRegret;
pub const DIVINE: Currency = Currency::DivineOrb;
pub const VAAL: Currency = Currency::VaalOrb;
